name: Update data

on:
  # Run every month on the 1st at 1:00 UTC
  schedule:
    - cron: "0 1 1 * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update-data.yml"
      - "config.php"
      - "data.csv"
      - "overpass/*"
  pull_request:
    paths:
      - ".github/workflows/update-data.yml"
      - "config.php"
      - "data.csv"
      - "overpass/*"

jobs:
  update-data:
    uses: EqualStreetNames/equalstreetnames/.github/reusable-workflows/update-date.yml@master
    with:
      city: belgium/brussels
